server {
  listen 80;
  server_name _;
  absolute_redirect off;

  root /usr/share/nginx/html;
  index index.html;

  location = / {
    return 302 /src/;
  }

  location = /src {
    return 301 /src/;
  }

  location /src/assets/ {
    try_files $uri =404;
    access_log off;
    add_header Cache-Control "public, max-age=31536000, immutable";
  }

  location /src/ {
    try_files $uri $uri/ /src/index.html;
  }

  location / {
    try_files $uri $uri/ /src/index.html;
  }
}
